version: '3.8'

services:
  hydroponics-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/hydroponics
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
